/* auto-generated by NAPI-RS */
/* eslint-disable */
/** OxideEngine - Main struct for GPU-accelerated ML operations using Candle */
export declare class OxideEngine {
  /** Create a new OxideEngine instance with Metal backend (macOS) or CPU fallback */
  constructor()
  /** Get device information as a string */
  getDeviceInfo(): string
  /**
   * Test GPU compute capability by performing a simple tensor operation
   * Creates two tensors on the GPU, adds them, and returns the result
   */
  testGpuCompute(): string
  /** Perform a more complex computation: element-wise multiplication */
  testMultiply(a: number, b: number): string
  /** Create a simple tensor and return its shape information */
  createTensorInfo(values: Array<number>): string
}
