/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Get detailed GPU capabilities */
export declare function getGpuCapabilities(): GpuCapabilities

/** Struct representing GPU capabilities (exported to Node.js) */
export interface GpuCapabilities {
  name: string
  backend: string
  maxTextureDimension2D: number
  maxBindGroups: number
  maxBufferSize: number
  supportsTimestamps: boolean
}

/** Initialize WebGPU adapter and return GPU information */
export declare function initializeWebgpu(): string

/** Get available GPU adapters without initializing */
export declare function listAdapters(): Array<string>
